FROM python:3-alpine

LABEL maintainer "ruben.vasconcelos3@mail.dcu.ie"

# Update and patch system
RUN apk update \
    && apk add \
      git \
      docker

ENV PYTHONPATH /app

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN python setup.py install
