version: '3.4'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik_default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.backend=portainer
        - traefik.port=9000
        - traefik.frontend.rule=Host:portainer.demo
        - traefik.docker.network=traefik_default

networks:
  traefik_default:
    external: true
  agent_network:
    driver: overlay

volumes:
  portainer_data:
